//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peliculas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peliculas
    {
        public int idPeliculas { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public string titulo { get; set; }
        public string signosis { get; set; }
        public string calificacion { get; set; }
        public Nullable<int> ano { get; set; }
        public string idioma { get; set; }
        public string genero { get; set; }
    }
}
